kazarm/grocery/urls.py
from django.urls import path, include
from . import views

app_name = 'grocery'

urlpatterns = [
    path('', views.first_stage_list, name='product-list'),
    path('add-product/', views.first_stage_create, name='f_s_create'),
    path('edit/<int:f_s_id>/', views.first_stage_edit, name='f_s_edit'),
    path('add-type-product/', views.product_create, name='product_type_add'),
    path('containers/', views.container_list, name='containers_list'),
    path('containers/create/', views.container_create, name='container_create'),
    path('containers/edit/<int:container_id>', views.container_edit, name='container_edit'),
    path('edit-product/<int:product_id>', views.product_edit, name='product_edit'),
    path('warehouse/<int:warehouse_id>', views.warehouse_container_list, name='warehouse_containers_list'),
    path('warehouse/list', views.warehouse_list, name='warehouse_list'),

    path('containers/<int:title>', views.containers_list_by_title, name='containers_list_by_title'),


    path('containers/list/date/<int:year>/<int:month>/<int:day>', views.containers_list_by_date_create, name='containers_list_by_date'),
    path('containers/list/date/update/<int:year>/<int:month>/<int:day>', views.containers_list_by_date_update,
         name='containers_list_by_date_update'),

    path('containers/list/status/<int:num>/<str:status>', views.containers_list_by_status, name='containers_list_by_status'),
    path('arrival/filter/', views.arrival_filter, name='arrival_filter'),

    path('arrivals/date/create/<int:year>/<int:month>/<int:day>', views.arrival_by_date_create, name='arrivals_date_create'),
    path('arrivals/date/update/<int:year>/<int:month>/<int:day>', views.arrival_by_date_update,
         name='arrivals_date_update'),
    path('arrivals/<str:auto>', views.arrival_by_auto, name='arrivals_by_auto'),
    path('arrivals/title/<str:title>', views.arrival_by_title, name='arrivals_by_title'),


    path('trays/', views.list_trays, name='trays_list'),
    path('trays/create/', views.tray_create, name='tray_create'),
    path('trays/filter/', views.tray_filter, name='tray_filter'),
    path('trays/edit/<int:id>', views.tray_edit, name='tray_edit'),
]

kazarm/kazarm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('grocery.urls')),
    path('account/', include('account.urls')),
    path('report/', include('report.urls'))

]

kazarm/report/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = 'report'


urlpatterns = [
    path('day', views.calc_day, name='report-day'),

    path('store/<int:id>', views.report_store, name='report_store'),
    path('stores/', views.stores, name='stores'),

    path('<int:year>/<int:month>/<int:day>', views.report, name='report'),

    path('first_stage_day/<int:year>/<int:month>/<int:day>', views.first_stage_day_report,
         name='first_day_report'),
    path('second_stage_day/<int:year>/<int:month>/<int:day>', views.second_stage_day_report,
         name='second_day_report'),


    path('filter_page/', views.filter_page, name='filter_page')

]

kazarm/report/models.py
from django.db import models

# Create your models here.

kazarm/report/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.db.models import Avg, Count, Sum, Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
import datetime
from grocery.models import *
from .filters import ContainerFilter

@login_required
def report(request, year, month, day):
    container_list = Container.objects.filter(created__year=year, created__month=month, created__day=day).filter(
        status='Отгружено')
    product_list = Product.objects.all()
    store_list = Store.objects.all()
    data_list = []
    date = datetime.datetime(year=year, month=month, day=day)
    for i in product_list:
        items = container_list.filter(title=i)
        if items:
            netto = items.aggregate(Sum('mass1'))['mass1__sum'] - items.aggregate(Sum('box_mass1'))['box_mass1__sum']
        else:
            netto = 0
        data_list.append([i, netto, items])

    date_list2 = []
    for i in store_list:
        store_item = container_list.filter(stores=i)
        if store_item:
            date_list2.append([i, len(store_item)])

    return render(request,
                  'time_report/report.html',
                  {'data_list': data_list,
                   'data_list2': date_list2,
                   'date': date})


@login_required
def stores(request):
    stores = Store.objects.all()
    return render(request,
                  'grocery/stores/stores.html',
                  {'stores': stores})


@login_required
def report_store(request, id):
    store = get_object_or_404(Store, id=id)
    store_trays = store.tray.all().order_by('-id')

    paginator = Paginator(store_trays, 20)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    return render(request,
                  'grocery/stores/store_report.html',
                  {'posts': posts,
                   'page': page,
                   'store': store})


@login_required
def calc_day(request):
    today = datetime.datetime.today()
    data_list1 = []
    data_list2 = []

    prods = Product.objects.all()
    container_list = Container.objects.all()
    for i in range(0, 7):
        data = today - datetime.timedelta(days=i)
        f_s_obj = First_stage.objects.all().filter(created__year=data.year, created__month=data.month, created__day=data.day)
        containers_obj = container_list.filter(created__year=data.year, created__month=data.month, created__day=data.day).filter(Q(status='Склад'))
        containers_trash = container_list.filter(created__year=data.year, created__month=data.month, created__day=data.day).filter(Q(status='Отходы'))
        if containers_obj:
            m1 = containers_obj.aggregate(Sum('mass1'))['mass1__sum'] - containers_obj.aggregate(Sum('box_mass1'))[
                'box_mass1__sum']
        else:
            m1 = 0
        if f_s_obj:
            m2 = f_s_obj.aggregate(Sum('first_m'))['first_m__sum'] - f_s_obj.aggregate(Sum('second_m'))['second_m__sum']
        else:
            m2 = 0
        if containers_trash:
            m_trash = containers_trash.aggregate(Sum('mass1'))['mass1__sum'] - containers_trash.aggregate(Sum('box_mass1'))[
                'box_mass1__sum']
        else:
            m_trash = 0
        diff_m1_m2_trash = m1 - m2 + m_trash
        among_cont = len(containers_obj)
        among_f_s = len(f_s_obj)
        data_list1.append([data, m1, m2, m_trash, diff_m1_m2_trash, among_cont, among_f_s])

        trays = Tray.objects.all()
        containers_sort = container_list.filter(updated__year=data.year, updated__month=data.month, updated__day=data.day).filter(status1='Сортировка')
        trays = trays.filter(created__year=data.year, created__month=data.month, created__day=data.day).filter(status='Склад')
        if containers_sort:
            netto2 = containers_sort.aggregate(Sum('mass2'))['mass2__sum'] - \
                     containers_sort.aggregate(Sum('box_mass2'))['box_mass2__sum']
            nett2_1 = containers_sort.aggregate(Sum('mass1'))['mass1__sum'] - \
                      containers_sort.aggregate(Sum('box_mass1'))['box_mass1__sum']
            different_1 = netto2 - nett2_1
        else:
            netto2 = 0
            different_1 = 0
        if trays:
            trays_netto = trays.aggregate(Sum('mass1'))['mass1__sum'] - trays.aggregate(Sum('mass2'))['mass2__sum']
        else:
            trays_netto = 0
        data_list2.append([data, netto2, different_1, trays_netto, trays_netto - netto2])

    return render(request,
                  'time_report/day.html',
                  {'data_list1': data_list1,
                   'data_list2': data_list2,
                   })


@login_required
def first_stage_day_report(request, year, month, day):
    container_list = Container.objects.filter(created__year=year, created__month=month, created__day=day).filter(Q(status='Отходы') | Q(status='Склад')).order_by('-id')
    arrivals = First_stage.objects.filter(created__year=year, created__month=month, created__day=day).order_by('-id')
    date = datetime.datetime(year=year, month=month, day=day)

    products_list = Product.objects.all()
    product_calc = []
    arrivals_calc = []
    for i in products_list:
        items = container_list.filter(title=i)
        if items:
            netto = items.aggregate(Sum('mass1'))['mass1__sum'] - items.aggregate(Sum('box_mass1'))['box_mass1__sum']
        else:
            netto = 0
        product_calc.append([i, netto])

    for i in products_list:
        items = arrivals.filter(title=i)
        if items:
            netto = items.aggregate(Sum('first_m'))['first_m__sum'] - items.aggregate(Sum('second_m'))[
                'second_m__sum']
        else:
            netto = 0
        arrivals_calc.append([i, netto])

    return render(request, 'time_report/first_stage_day_report.html',
                  {'container_list': container_list,
                   'arrivals': arrivals,
                   'date': date,
                   'product_calc': product_calc,
                   'arrivals_calc': arrivals_calc})


@login_required
def second_stage_day_report(request, year, month, day):
    container_list = Container.objects.filter(updated__year=year, updated__month=month, updated__day=day).order_by('-id')
    container_list_sort = container_list.filter(status1='Сортировка')
    date = datetime.datetime(year=year, month=month, day=day)
    product_list = Product.objects.all()
    product_sort_calc = []
    trays_product_calc = []
    tray_list = Tray.objects.filter(created__year=year, created__month=month, created__day=day).filter(status='Склад')

    for i in product_list:
        items1 = container_list_sort.filter(title=i)
        if items1:
            netto1 = items1.aggregate(Sum('mass1'))['mass1__sum'] - items1.aggregate(Sum('box_mass1'))['box_mass1__sum']
            netto2 = items1.aggregate(Sum('mass2'))['mass2__sum'] - items1.aggregate(Sum('box_mass2'))['box_mass2__sum']
            diff1 = netto2 - netto1
        else:
            netto1 = 0
            netto2 = 0
            diff1 = 0
        product_sort_calc.append([i, netto1, netto2, diff1])

        items2 = tray_list.filter(title=i)
        if items2:
            netto1 = items2.aggregate(Sum('mass1'))['mass1__sum'] - items2.aggregate(Sum('mass2'))['mass2__sum']
        else:
            netto1 = 0
        trays_product_calc.append([i.title, netto1])
    return render(request,
                  'time_report/second_stage_day_report.html',

                  {'container_list_sort': container_list_sort,
                   'date': date,
                   'product_sort_calc': product_sort_calc,
                   'tray_list': tray_list,
                   'trays_product_calc': trays_product_calc})


@login_required
def filter_page(request):
    container_list = Container.objects.all().order_by('-id')
    myFilter = ContainerFilter(request.GET, queryset=container_list)

    table = list_container(myFilter.qs)

    paginator = Paginator(myFilter.qs, 10)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    return render(request, 'filter/filter_container_page.html', {'page': page, 'myFilter': myFilter, 'posts': posts, 'table': table})


def list_container(models):
    table_data = []
    products = Product.objects.all()
    for i in products:
        containers = models.filter(title=i)
        if containers:
            m1 = containers.aggregate(Sum('mass1'))['mass1__sum'] - containers.aggregate(Sum('box_mass1'))['box_mass1__sum']
            m2 = containers.aggregate(Sum('mass2'))['mass2__sum'] - containers.aggregate(Sum('box_mass2'))['box_mass2__sum']
            table_data.append([i, m1, m2])
        else:
            table_data.append([i, 0, 0])
    return table_data

kazarm/report/templates/time_report/day.html
{% extends 'base.html' %}
{% block title %} Hello {% endblock %}
{% block content%}
<div class="container">
    <div class="row">
        <h2>Отчет</h2>

        <div class="table-responsive col-12">
        <h3>Отчет по приходу с поля</h3>
        <table class="table table-striped table-sm">
            <thead>
                <tr>
{#                    <th>#</th>#}
                    <th>Дата</th>
                    <th>Приход</th>
                    <th>Вес продукции</th>
                    <th>Масса земля/мусор</th>
                    <th>Разница</th>
                    <th>Количество приходов</th>
                    <th>Количество контейнеров</th>
                </tr>
            </thead>
            <tbody>

            {% for i in data_list1 %}
                <tr>
                    <td><a href="{% url 'report:first_day_report' year=i.0.year month=i.0.month day=i.0.day %}">{{ i.0|date:"d.m.y" }}</a></td>
                    <td>{{ i.2 }}</td>
                    <td>{{ i.1 }}</td>
                    <td>{{ i.3 }}</td>
                    <td>{{ i.4 }}</td>
                    <td>{{ i.6 }}</td>
                    <td>{{ i.5 }}</td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
        </div>
        <div class="table-responsive col-12">
        <h3>Отчет выемки со склада</h3>
        <table class="table table-striped table-sm">
            <thead>
                <tr>
{#                    <th>#</th>#}
                    <th>Дата</th>
                    <th>Нетто Сортировки</th>
                    <th>Потеря первой сортировки</th>
                    <th>Нетто Поддонов</th>
                    <th>Потеря второй сортировки</th>
                </tr>
            </thead>
            <tbody>

            {% for i in data_list2 %}
                <tr>
                    <td><a href="{% url 'report:second_day_report' year=i.0.year month=i.0.month day=i.0.day %}">{{ i.0|date:"d.m.y" }}</a></td>
                    <td>{{ i.1}}</td>
                    <td>{{ i.2 }}</td>
                    <td>{{ i.3 }}</td>
                    <td>{{ i.4 }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        </div>
    </div>
</div>
{% endblock %}

kazarm/report/templates/time_report/first_stage_day_report.html
{% extends 'base.html' %}
{% block title %} Hello {% endblock %}
{% block content %}

    <div class="container">

        <div class="row">
            <h3>Отчет по приходу с поля {{ date|date:"d.m.y" }}</h3>
            <div class="table-responsive col-12">
                <h4>Контейнера</h4>
                <table class="table table-striped table-sm">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Продукт</th>
                            <th>Дата создания</th>
                            <th>Время</th>
                            <th>Дата изменения</th>
                            <th>Время</th>
                            <th>Статус</th>
                            <th>Место нахождения</th>
                            <th>Брутто1</th>
                            <th>Нетто1</th>
                            <th>Брутто2</th>
                            <th>Нетто2</th>
                            <th>Разница </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in container_list %}
                            <tr>
                                <td><a href="{% url 'grocery:container_edit' i.id %}">{{ i.id }}</a></td>
                                <td>{{ i.title }}</td>
                                <td><a href="{% url 'grocery:containers_list_by_date' year=i.created.year month=i.created.month day=i.created.day %}">{{ i.created|date:"d.m.y" }}</a></td>
                                <td>{{ i.created|time}}</td>
                                <td><a href="{% url 'grocery:containers_list_by_date_update' year=i.updated.year month=i.updated.month day=i.updated.day  %}">{{ i.updated|date:"d.m.y" }}</a></td>
                                <td>{{ i.updated|time }}</td>
                                {% if i.status1 != ' '%}
                                    <td><a href="{% url 'grocery:containers_list_by_status' num=2 status=i.status1%}">{{ i.status1 }}</a></td>
                                {% else %}
                                    <td><a href="{% url 'grocery:containers_list_by_status' num=1 status=i.status%}">{{ i.status }}</a></td>
                                {% endif %}
                                <td><a href="{% url 'grocery:warehouse_containers_list' i.warehouse.id  %}">{{ i.warehouse }}</a></td>
                                <td>{{ i.mass1 }}</td>
                                <td>{{ i.calc_netto1 }}</td>
                                <td>{{ i.mass2 }}</td>
                                <td>{{ i.calc_netto2 }}</td>

                                {% if i.mass2 == 0 %}
                                    <td>0</td>
                                {% else %}
                                    <td>{{ i.calc_mass }}</td>
                                {% endif %}
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
            </div>
        </div>

        <div class="row">
            <div class="table-responsive col-12">
                <h4>Общая масса по контейнерам</h4>
                <table class="table table-striped table-sm">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Продукт</th>
                        <th>Нетто</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for i in product_calc %}
                        {% if i.1 != 0 %}
                        <tr>
                            <td>{{ i.0.id }}</td>
                            <td>{{ i.0.title }}</td>
                            <td>{{ i.1 }}</td>
                        </tr>
                        {% endif %}
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>


        <div class="row">
            <div class="table-responsive col-12">
                <h4>Приход</h4>
                <table class="table table-striped table-sm">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Продукт</th>
                            <th>Номер машины</th>
                            <th>Дата прихода</th>
                            <th>Время</th>
                            <th>Дата ухода</th>
                            <th>Время</th>
                            <th>Масса груза</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in arrivals %}
                            <tr>
                                <td><a href="{% url 'grocery:f_s_edit' i.id %}">{{ i.id }}</a></td>
                                <td>{{ i.title }}</td>
                                <td>{{ i.numbers_auto }}</td>
                                <td>{{ i.created|date:"d.m.y" }}</td>
                                <td>{{ i.created|time}}</td>
                                <td>{{ i.updated|date:"d.m.y" }}</td>
                                <td>{{ i.updated|time }}</td>
                                <td>{{ i.calc }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <div class="row">
            <div class="table-responsive col-12">
                <h4>Общая масса по приходу</h4>
                <table class="table table-striped table-sm">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Продукт</th>
                        <th>Нетто</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for i in arrivals_calc %}
                        {% if i.1 != 0 %}
                        <tr>
                            <td>{{ i.0.id }}</td>
                            <td>{{ i.0.title }}</td>
                            <td>{{ i.1 }}</td>
                        </tr>
                        {% endif %}
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

kazarm/report/templates/time_report/report.html
{% extends 'base.html' %}
{% block title %} Hello {% endblock %}
{% block content %}

    <div class="container">
        <div class="row">
            <h3>Отчет продаж {{ date|date:"d.m.y" }}</h3>
            <div class="table-responsive col-12">
                <table class="table table-striped table-sm">
                    <thead>
                        <tr>
                            <th>Продукт</th>
                            <th>Масса Нетто</th>
                            <th>Количество контейнеров</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in data_list %}
                            <tr>
                                <td>{{ i.0 }}</td>
                                <td>{{ i.1 }}</td>
                                <td>{{ i.2|length }}</td>
                            </tr>
                        {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>


        <div class="row">
            <div class="table-responsive col-12">
                <table class="table table-striped table-sm">
                    <thead>
                        <tr>
                            <th>Компания</th>
                            <th>Количество контейнеров</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in data_list2 %}
                            <tr>
                                <td><a href="{% url 'grocery:report_store' i.0.id  %}">{{ i.0 }}</a></td>
                                <td>{{ i.1 }}</td>
                            </tr>
                        {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>


{% endblock %}

kazarm/report/templates/time_report/second_stage_day_report.html
{% extends 'base.html' %}
{% block title %} Hello {% endblock %}
{% block content %}

    <div class="container">

        <div class="row">
            <h3>Отчет выемки со склада {{ date|date:"d.m.y" }}</h3>
            <div class="table-responsive col-12">
                <h4>Контейнера</h4>
                <table class="table table-striped table-sm">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Продукт</th>
                            <th>Время создания</th>
                            <th>Время изменения</th>
                            <th>Статус</th>
                            <th>Место нахождения</th>
                            <th>Брутто1</th>
                            <th>Нетто1</th>
                            <th>Брутто2</th>
                            <th>Нетто2</th>
                            <th>Разница </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in container_list_sort %}
                            <tr>
                                <td><a href="{% url 'grocery:container_edit' i.id %}">{{ i.id }}</a></td>
                                <td>{{ i.title }}</td>
                                <td>{{ i.created }}</td>
                                <td>{{ i.updated }}</td>
                                {% if i.status1 %}
                                    <td><a href="{% url 'grocery:containers_list_by_status' num=2 status=i.status1%}">{{ i.status1 }}</a></td>

                                {% else %}
                                    <td><a href="{% url 'grocery:containers_list_by_status' num=1 status=i.status%}">{{ i.status }}</a></td>
                                {% endif %}
                                <td><a href="{% url 'grocery:warehouse_containers_list' i.warehouse.id  %}">{{ i.warehouse }}</a></td>
                                <td>{{ i.mass1 }}</td>
                                <td>{{ i.calc_netto1 }}</td>
                                <td>{{ i.mass2 }}</td>
                                <td>{{ i.calc_netto2 }}</td>

                                {% if i.mass2 == 0 %}
                                    <td>0</td>
                                {% else %}
                                    <td>{{ i.calc_mass }}</td>
                                {% endif %}
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
            </div>
        </div>

        <div class="row">
            <div class="table-responsive col-12">
                <h4>Общая масса по контейнерам Сортировка</h4>
                <table class="table table-striped table-sm">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Продукт</th>
                        <th>Нетто1</th>
                        <th>Нетто2</th>
                        <th>Разница</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for i in product_sort_calc %}
                        {% if i.1 != 0 %}
                        <tr>
                            <td>{{ i.0.id }}</td>
                            <td>{{ i.0.title }}</td>
                            <td>{{ i.1 }}</td>
                            <td>{{ i.2 }}</td>
                            <td>{{ i.3}}</td>
                        </tr>
                        {% endif %}
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <div class="row">
            <h4>Поддоны</h4>
            <div class="col-md-12">
                <table class="table table-striped table-sm">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Продукт</th>
                            <th>Дата создания</th>
                            <th>Время</th>
                            <th>Дата изменения</th>
                            <th>Время</th>
                            <th>Статус</th>
                            <th>Место нахождения</th>
                            <th>Фасовка</th>
                            <th>Количество</th>
                            <th>Масса</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in tray_list %}
                            <tr>
                                <td><a href="{% url 'grocery:tray_edit' i.id %}">{{ i.id }}</a></td>
                                <td>{{ i.title }}</td>
                                <td>{{ i.created|date:"d.m.y" }}</td>
                                <td>{{ i.created|time}}</td>
                                <td>{{ i.updated|date:"d.m.y" }}</td>
                                <td>{{ i.updated|time }}</td>
                                {% if i.status1 != ' ' %}
                                    <td>{{ i.status1 }}</td>
                                {% else %}
                                    <td>{{ i.status }}</td>
                                {% endif %}
                                <td>{{ i.warehouse }}</td>
                                <td>{{ i.packing }}</td>
                                <td>{{ i.number_pr }}</td>
                                <td>{{ i.calc_netto }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <table class="table table-striped table-sm">
                    <thead>
                        <tr>
                            <th>Продукт</th>
                            <th>Масса</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in trays_product_calc %}
                            {% if i.1 != 0 %}
                            <tr>
                                <td>{{ i.0 }}</td>
                                <td>{{ i.1 }}</td>
                            </tr>
                            {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}