kazarm/grocery/urls.py
from django.urls import path, include
from . import views

app_name = 'grocery'

urlpatterns = [
    path('', views.first_stage_list, name='product-list'),
    path('add-product/', views.first_stage_create, name='f_s_create'),
    path('edit/<int:f_s_id>/', views.first_stage_edit, name='f_s_edit'),
    path('add-type-product/', views.product_create, name='product_type_add'),
    path('containers/', views.container_list, name='containers_list'),
    path('containers/create/', views.container_create, name='container_create'),
    path('containers/edit/<int:container_id>', views.container_edit, name='container_edit'),
    path('edit-product/<int:product_id>', views.product_edit, name='product_edit'),
    path('warehouse/<int:warehouse_id>', views.warehouse_container_list, name='warehouse_containers_list'),
    path('warehouse/list', views.warehouse_list, name='warehouse_list'),

    path('containers/<int:title>', views.containers_list_by_title, name='containers_list_by_title'),


    path('containers/list/date/<int:year>/<int:month>/<int:day>', views.containers_list_by_date_create, name='containers_list_by_date'),
    path('containers/list/date/update/<int:year>/<int:month>/<int:day>', views.containers_list_by_date_update,
         name='containers_list_by_date_update'),

    path('containers/list/status/<int:num>/<str:status>', views.containers_list_by_status, name='containers_list_by_status'),
    path('arrival/filter/', views.arrival_filter, name='arrival_filter'),

    path('arrivals/date/create/<int:year>/<int:month>/<int:day>', views.arrival_by_date_create, name='arrivals_date_create'),
    path('arrivals/date/update/<int:year>/<int:month>/<int:day>', views.arrival_by_date_update,
         name='arrivals_date_update'),
    path('arrivals/<str:auto>', views.arrival_by_auto, name='arrivals_by_auto'),
    path('arrivals/title/<str:title>', views.arrival_by_title, name='arrivals_by_title'),


    path('trays/', views.list_trays, name='trays_list'),
    path('trays/create/', views.tray_create, name='tray_create'),
    path('trays/filter/', views.tray_filter, name='tray_filter'),
    path('trays/edit/<int:id>', views.tray_edit, name='tray_edit'),
]

kazarm/kazarm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('grocery.urls')),
    path('account/', include('account.urls')),
    path('report/', include('report.urls'))

]

kazarm/report/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = 'report'


urlpatterns = [
    path('day', views.calc_day, name='report-day'),

    path('store/<int:id>', views.report_store, name='report_store'),
    path('stores/', views.stores, name='stores'),

    path('<int:year>/<int:month>/<int:day>', views.report, name='report'),

    path('first_stage_day/<int:year>/<int:month>/<int:day>', views.first_stage_day_report,
         name='first_day_report'),
    path('second_stage_day/<int:year>/<int:month>/<int:day>', views.second_stage_day_report,
         name='second_day_report'),


    path('filter_page/', views.filter_page, name='filter_page')

]

kazarm/grocery/forms.py
from django import forms
from .models import First_stage, Product, Container, Tray


class first_stage_form(forms.ModelForm):
    class Meta:
        model = First_stage
        fields = ('title', 'numbers_auto', 'first_m', 'second_m')
        labels = {
            'title': ('Название продукта'),
            'numbers_auto': ('Номер машины'),
            'first_m': ('Вес груженной машины'),
            'second_m': ('Вес машины')
        }


class first_stage_edit_form(forms.ModelForm):
    class Meta:
        model = First_stage
        fields = ('title', 'numbers_auto', 'first_m', 'second_m')
        labels = {
            'title': ('Название продукта'),
            'numbers_auto': ('Номер машины'),
            'first_m': ('Первый груз вес'),
            'second_m': ('Второй груз вес')
        }


class product_add_form(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('title',)
        labels = {
            'title': ('Название продукта')
        }


class container_create_form(forms.ModelForm):
    class Meta:
        model = Container
        fields = ('title', 'mass1',  'box_mass1', 'status', 'warehouse')
        labels = {
            'title': ('Название продукта'),
            'mass1':('Вес продукта с тарой'),
            'status': ('Статус'),
            'warehouse': ('Место'),
            # 'mass2': ('Масса2'),
            'box_mass1':('Вес тары'),
            # 'box_mass2':('Вторая масса бокса'),
            # 'stores': ('место отгрузки')
        }


class container_edit_form(forms.ModelForm):
    class Meta:
        model = Container
        fields = ('status1', 'mass2', 'box_mass2', 'stores')
        labels = {
            'title': ('Название продукта'),
            'mass1':('Вес продукта с тарой'),
            'status1': ('Статус'),
            'warehouse': ('Место'),
            'mass2': ('Вес продукта с тарой'),
            'box_mass1':('Вес тары'),
            'box_mass2':('Вес тары'),
            'stores': ('место отгрузки')
        }


class product_edit_form(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('title',)
        labels = {'title': 'Название'}


class tray_create_form(forms.ModelForm):
    class Meta:
        model = Tray
        fields = ('title', 'status', 'mass1', 'mass2', 'packing', 'warehouse', 'number_pr', 'stores')
        labels = {
            'title': ('Название продукта'),
            'mass1': ('Вес продукта с поддоном'),
            'mass2': ('Вес поддона'),
            'status1': ('Статус'),
            'status': ('Статус'),
            'warehouse': ('Место'),
            'packing': ('тип фасовки'),
            'number_pr': ('количество'),
            'stores': ('место отгрузки')
        }


class tray_edit_form(forms.ModelForm):
    class Meta:
        model = Tray
        fields = ('status1', 'stores')

kazarm/grocery/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from .models import Product, First_stage, Container, Warehouse, Store, Tray
from .forms import *
from django.urls import reverse
from django.db.models import Avg, Count, Sum, Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
import datetime
from .filters import TrayFilter, ArrivalFilter
from report.views import list_container


@login_required
def first_stage_list(request):
    today = datetime.datetime.today()
    products = Product.objects.all()
    f_s = First_stage.objects.all().order_by('-id')
    calc_mass = []
    different_mass = 0
    for i in products:
        all_obj = First_stage.objects.filter(created__year=today.year, created__month=today.month, created__day=today.day,).filter(title=i)
        if all_obj:
            different_mass = all_obj.aggregate(Sum('first_m'))['first_m__sum'] - all_obj.aggregate(Sum('second_m'))[
                'second_m__sum']
        else:
            different_mass = 0
        calc_mass.append(different_mass)

    paginator = Paginator(f_s, 50)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    product_mass = dict(zip(products, calc_mass))
    return render(request,
                  'grocery/first_stage/main.html',
                  {'products': products,
                   'page': page,
                   'product_mass': product_mass.items(),
                   'f_s': posts})


@login_required
def first_stage_create(request):
    if request.method == 'POST':
        create_product = first_stage_form(data=request.POST)
        if create_product.is_valid():
            create_post_form = create_product.save(commit=False)
            create_post_form.save()
            return HttpResponseRedirect(reverse('grocery:product-list'))
    else:
        create_post_form = first_stage_form()

    return render(request, 'grocery/first_stage/add_item.html', {
        'post_form': create_post_form,
    })


@login_required
def first_stage_edit(request, f_s_id):
    post = get_object_or_404(First_stage, id=f_s_id)
    if request.method == 'POST':
        post_form = first_stage_edit_form(data=request.POST, instance=post)

        if post_form.is_valid():
            post_form = post_form.save(commit=False)
            post_form.save()
            return HttpResponseRedirect(reverse('grocery:product-list'))
    else:
        post_form = first_stage_edit_form(instance=post)

    return render(request,
                  'grocery/first_stage/edit_item.html',
                  {'post_form': post_form})


@login_required
def product_create(request):
    if request.method == 'POST':
        add_type_product = product_add_form(data=request.POST)
        if add_type_product.is_valid():
            add_type_product = add_type_product.save(commit=False)
            add_type_product.save()
            return HttpResponseRedirect(reverse('grocery:product-list'))
    else:
        add_type_product = product_add_form()

    return render(request, 'grocery/first_stage/add_product.html', {
        'post_form': add_type_product,
    })


@login_required
def container_list(request):
    containers = Container.objects.all().order_by('-id')

    paginator = Paginator(containers, 50)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    return render(request,
                  'grocery/containers/list.html',
                  {'page': page,
                   'posts': posts
                   })


@login_required
def container_create(request):
    if request.method == 'POST':
        create_container = container_create_form(data=request.POST)
        if create_container.is_valid():
            create_container = create_container.save(commit=False)
            create_container.save()
            return HttpResponseRedirect(reverse('grocery:containers_list'))
    else:
        create_container = container_create_form()

    return render(request, 'grocery/containers/add_item.html', {
        'post_form': create_container,
    })


@login_required
def container_edit(request, container_id):
    container = get_object_or_404(Container, id=container_id)
    if request.method == 'POST':
        container_form = container_edit_form(data=request.POST, instance=container)

        if container_form.is_valid():
            container_form = container_form.save(commit=False)
            container_form.save()
            return HttpResponseRedirect(reverse('grocery:containers_list'))
    else:
        container_form = container_edit_form(instance=container)

    return render(request,
                  'grocery/containers/edit_item.html',
                  {'post_form': container_form})


@login_required
def product_edit(request, product_id):
    product = get_object_or_404(Product, id=product_id)

    if request.method == 'POST':
        product_form = product_edit_form(data=request.POST, instance=product)

        if product_form.is_valid():
            product_form = product_form.save(commit=False)
            product_form.save()
            return HttpResponseRedirect(reverse('grocery:product-list'))
    else:
        product_form = product_edit_form(instance=product)

    return render(request,
                  'grocery/first_stage/edit_product.html',
                  {'post_form': product_form})


@login_required
def warehouse_container_list(request, warehouse_id):
    warehouse = get_object_or_404(Warehouse, id=warehouse_id)
    title = warehouse.title
    containers = warehouse.container.all().order_by('-id')
    containers = containers.filter(Q(status='Отходы') | Q(status='Склад'))
    paginator = Paginator(containers, 30)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)


    trays = Tray.objects.filter(status='Склад').filter(status1=' ').order_by('-id')

    paginator1 = Paginator(trays, 30)
    page1 = request.GET.get('page')
    try:
        posts1 = paginator1.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts1 = paginator1.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts1 = paginator1.page(paginator.num_pages)


    return render(request,
                  'grocery/warehouse/list_containers.html',
                  {'page': page,
                   'posts': posts,
                   'title': title,
                   'page1': page1,
                   'posts1': posts1
                   })


@login_required
def warehouse_list(request):
    warehouses = Warehouse.objects.all()
    table = []
    for i in warehouses:
        container_list = i.container.filter(status='Склад').filter(status1=' ')
        tray_list = i.tray.filter(status='Склад').filter(status1=' ')
        if container_list:
            container_mass = container_list.aggregate(Sum('mass1'))['mass1__sum'] - container_list.aggregate(Sum('box_mass1'))['box_mass1__sum']
        else:
            container_mass = 0

        if tray_list:
            tray_mass = tray_list.aggregate(Sum('mass1'))['mass1__sum'] - tray_list.aggregate(Sum('mass2'))['mass2__sum']
        else:
            tray_mass = 0

        tray_net = tray_list.filter(packing='Сетка')
        tray_bag = tray_list.filter(packing='Мешок')
        if tray_net:
            tray_net_num = tray_list.filter(packing='Сетка').aggregate(Sum('number_pr'))['number_pr__sum']
        else:
            tray_net_num = 0
        if tray_bag:
            tray_bag_num = tray_list.filter(packing='Мешок').aggregate(Sum('number_pr'))['number_pr__sum']
        else:
            tray_bag_num = 0

        table.append([i, container_mass, tray_mass, tray_net_num, tray_bag_num])

    paginator = Paginator(table, 30)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    return render(request,
                  'grocery/warehouse/list_warehouse.html',
                  {'page': page,
                   'posts': posts})


@login_required
def containers_list_by_title(request, title):
    container_list = Container.objects.filter(title=title).order_by('-id')
    paginator = Paginator(container_list, 20)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    return render(request,
                  'grocery/containers/list_by_title.html',
                  {'container_list': posts,
                   'page': page})


@login_required
def containers_list_by_date_create(request, year, month, day):

kazarm/grocery/templates/grocery/containers/add_item.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <form  method="POST">
                {% csrf_token %}
                {{ post_form.as_p }}
                <p>
                    <input class="btn btn-primary " type="submit" value="Создать">
                </p>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

kazarm/grocery/templates/grocery/containers/edit_item.html
{% extends 'base.html' %}

{% block title %}Edit post{% endblock %}
{% block content %}

<div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                    <form method="POST">
                        {% csrf_token %}
                        {{ post_form.as_p }}
                        <p>
                                <input class="btn btn-primary" type="submit" value="Изменить">
                        </p>
                    </form>

            </div>
        </div>
    </div>

{% endblock %}

kazarm/grocery/templates/grocery/containers/list.html
{% extends 'base.html' %}
{% block title %} Hello {% endblock %}
{% block content%}
<div class="container">
    <div class="row">
        <h2>Таблица контейнеров</h2>
        <nav>
            <a class="btn btn-outline-primary" href="{% url 'grocery:container_create' %}">Создать контейнер</a>
            <a class="btn btn-outline-primary" href="{% url 'grocery:product_type_add' %}">Создать продукт</a>
            <a class="btn btn-outline-primary" href="{% url 'report:filter_page' %}">Фильтр</a>

        </nav>
        <div class="table-responsive col-12">
        <h3>Таблица контейнеров</h3>
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                  <th>#</th>
                  <th>Продукт</th>
                  <th>Дата создания</th>
                  <th>Время</th>
                  <th>Дата изменения</th>
                  <th>Время</th>
                  <th>Статус</th>
                  <th>Место нахождения</th>
                  <th>Брутто1</th>
                  <th>Нетто1</th>
                  <th>Брутто2</th>
                  <th>Нетто2</th>
                  <th>Разница </th>

                </tr>
            </thead>
            <tbody>
                {% for i in posts %}
                <tr>
                    <td><a href="{% url 'grocery:container_edit' i.id %}">{{ i.id }}</a></td>
                    <td><a href="{% url 'grocery:containers_list_by_title' i.title.id %}">{{ i.title }}</a></td>
                    <td><a href="{% url 'grocery:containers_list_by_date' year=i.created.year month=i.created.month day=i.created.day %}">{{ i.created|date:"d.m.y" }}</a></td>
                    <td>{{ i.created|time}}</td>
                    <td><a href="{% url 'grocery:containers_list_by_date_update' year=i.updated.year month=i.updated.month day=i.updated.day  %}">{{ i.updated|date:"d.m.y" }}</a></td>
                    <td>{{ i.updated|time }}</td>
                    {% if i.status1 != ' ' %}
                        <td><a href="{% url 'grocery:containers_list_by_status' num=2 status=i.status1%}">{{ i.status1 }}</a></td>

                    {% else %}
                        <td><a href="{% url 'grocery:containers_list_by_status' num=1 status=i.status%}">{{ i.status }}</a></td>
                    {% endif %}
                    <td><a href="{% url 'grocery:warehouse_containers_list' i.warehouse.id  %}">{{ i.warehouse }}</a></td>
                    <td>{{ i.mass1 }}</td>
                    <td>{{ i.calc_netto1 }}</td>
                    <td>{{ i.mass2 }}</td>
                    <td>{{ i.calc_netto2 }}</td>

                    {% if i.mass2 == 0 %}
                        <td>0</td>
                    {% else %}
                        <td>{{ i.calc_mass }}</td>
                    {% endif %}

                </tr>
                {% endfor %}
                {% include "pagination.html" with page=posts %}

            </tbody>
        </table>

        </div>
    </div>
</div>
{% endblock %}

kazarm/grocery/templates/grocery/containers/list_by_date.html
{% extends 'base.html' %}
{% block title %} Hello {% endblock %}
{% block content %}

    <div class="container">
        <div class="row">
            <h3>Контейнеры за {{ date|date:"d.m.y" }}</h3>
            <div class="table-responsive col-12">
                <table class="table table-striped table-sm">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Продукт</th>
                            <th>Время создания</th>
                            <th>Время изменения</th>
                            <th>Статус</th>
                            <th>Место нахождения</th>
                            <th>Брутто1</th>
                            <th>Нетто1</th>
                            <th>Брутто2</th>
                            <th>Нетто2</th>
                            <th>Разница </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in container_list %}
                        <tr>
                            <td><a href="{% url 'grocery:container_edit' i.id %}">{{ i.id }}</a></td>
                            <td>{{ i.title }}</td>
                            <td>{{ i.created }}</td>
                            <td>{{ i.updated }}</td>
                            {% if i.status1 != ' '%}
                                <td><a href="{% url 'grocery:containers_list_by_status' num=2 status=i.status1%}">{{ i.status1 }}</a></td>
                            {% else %}
                                <td><a href="{% url 'grocery:containers_list_by_status' num=1 status=i.status%}">{{ i.status }}</a></td>
                            {% endif %}
                            <td><a href="{% url 'grocery:warehouse_containers_list' i.warehouse.id  %}">{{ i.warehouse }}</a></td>
                            <td>{{ i.mass1 }}</td>
                            <td>{{ i.calc_netto1 }}</td>
                            <td>{{ i.mass2 }}</td>
                            <td>{{ i.calc_netto2 }}</td>

                            {% if i.mass2 == 0 %}
                                <td>0</td>
                            {% else %}
                                <td>{{ i.calc_mass }}</td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
{% endblock %}

kazarm/grocery/templates/grocery/containers/list_by_date_update.html
{% extends 'base.html' %}
{% block title %} Hello {% endblock %}
{% block content %}

    <div class="container">
        <div class="row">
            <h3>Контейнеры за {{ date|date:"d.m.y" }}</h3>
            <div class="table-responsive col-12">
                <table class="table table-striped table-sm">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Продукт</th>
                            <th>Время создания</th>
                            <th>Время изменения</th>
                            <th>Статус</th>
                            <th>Место нахождения</th>
                            <th>Брутто1</th>
                            <th>Нетто1</th>
                            <th>Брутто2</th>
                            <th>Нетто2</th>
                            <th>Разница </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in container_list %}
                        <tr>
                            <td><a href="{% url 'grocery:container_edit' i.id %}">{{ i.id }}</a></td>
                            <td>{{ i.title }}</td>
                            <td>{{ i.created }}</td>
                            <td>{{ i.updated }}</td>
                            {% if i.status1 != ' '%}
                                <td><a href="{% url 'grocery:containers_list_by_status' num=2 status=i.status1%}">{{ i.status1 }}</a></td>
                            {% else %}
                                <td><a href="{% url 'grocery:containers_list_by_status' num=1 status=i.status%}">{{ i.status }}</a></td>
                            {% endif %}
                            <td><a href="{% url 'grocery:warehouse_containers_list' i.warehouse.id  %}">{{ i.warehouse }}</a></td>
                            <td>{{ i.mass1 }}</td>
                            <td>{{ i.calc_netto1 }}</td>
                            <td>{{ i.mass2 }}</td>
                            <td>{{ i.calc_netto2 }}</td>

                            {% if i.mass2 == 0 %}
                                <td>0</td>
                            {% else %}
                                <td>{{ i.calc_mass }}</td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
{% endblock %}

kazarm/grocery/templates/grocery/containers/list_by_status.html
{% extends 'base.html' %}
{% block title %} Hello {% endblock %}
{% block content %}

    <div class="container">
        <div class="row">
            <h3>Контейнеры {{ status }}</h3>
            <div class="table-responsive col-12">
                <table class="table table-striped table-sm">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Продукт</th>
                            <th>Время создания</th>
                            <th>Время изменения</th>
                            <th>Статус</th>
                            <th>Место нахождения</th>
                            <th>Брутто1</th>
                            <th>Нетто1</th>
                            <th>Брутто2</th>
                            <th>Нетто2</th>
                            <th>Разница </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in container_list %}
                        <tr>
                            <td><a href="{% url 'grocery:container_edit' i.id %}">{{ i.id }}</a></td>
                            <td>{{ i.title }}</td>
                            <td>{{ i.created }}</td>
                            <td>{{ i.updated }}</td>
                            {% if i.status1 != ' '%}
                                <td><a href="{% url 'grocery:containers_list_by_status' num=2 status=i.status1%}">{{ i.status1 }}</a></td>
                            {% else %}
                                <td><a href="{% url 'grocery:containers_list_by_status' num=1 status=i.status%}">{{ i.status }}</a></td>
                            {% endif %}
                            <td><a href="{% url 'grocery:warehouse_containers_list' i.warehouse.id  %}">{{ i.warehouse }}</a></td>
                            <td>{{ i.mass1 }}</td>
                            <td>{{ i.calc_netto1 }}</td>
                            <td>{{ i.mass2 }}</td>
                            <td>{{ i.calc_netto2 }}</td>

                            {% if i.mass2 == 0 %}
                                <td>0</td>
                            {% else %}
                                <td>{{ i.calc_mass }}</td>
                            {% endif %}
                        </tr>
                        {% endfor %}

                        {% include "pagination.html" with page=container_list %}

                    </tbody>
                </table>
            </div>
        </div>
{% endblock %}

kazarm/grocery/templates/grocery/containers/list_by_title.html
{% extends 'base.html' %}
{% block title %} Hello {% endblock %}
{% block content %}

    <div class="container">
        <div class="row">
            <h3>Контейнеры продукта {{ container_list.0.title }}</h3>
            <div class="table-responsive col-12">
                <table class="table table-striped table-sm">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Продукт</th>
                            <th>Время создания</th>
                            <th>Время изменения</th>
                            <th>Статус</th>
                            <th>Место нахождения</th>
                            <th>Брутто1</th>
                            <th>Нетто1</th>
                            <th>Брутто2</th>
                            <th>Нетто2</th>
                            <th>Разница </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in container_list %}
                        <tr>
                            <td><a href="{% url 'grocery:container_edit' i.id %}">{{ i.id }}</a></td>
                            <td>{{ i.title }}</td>
                            <td>{{ i.created }}</td>
                            <td>{{ i.updated }}</td>
                            {% if i.status1 != ' '%}
                                <td><a href="{% url 'grocery:containers_list_by_status' num=2 status=i.status1%}">{{ i.status1 }}</a></td>
                            {% else %}
                                <td><a href="{% url 'grocery:containers_list_by_status' num=1 status=i.status%}">{{ i.status }}</a></td>
                            {% endif %}
                            <td><a href="{% url 'grocery:warehouse_containers_list' i.warehouse.id  %}">{{ i.warehouse }}</a></td>
                            <td>{{ i.mass1 }}</td>
                            <td>{{ i.calc_netto1 }}</td>
                            <td>{{ i.mass2 }}</td>
                            <td>{{ i.calc_netto2 }}</td>

                            {% if i.mass2 == 0 %}
                                <td>0</td>
                            {% else %}
                                <td>{{ i.calc_mass }}</td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                        {% include "pagination.html" with page=container_list %}

                    </tbody>
                </table>
            </div>
        </div>
{% endblock %}